# NumPy basics — my revision notes

I wrote these so I can come back and revise without re-learning from scratch.
Each section is: **what I need to remember**, then the code I already ran.

**How to revise**
1. Read the bullets. Cover the code and try to predict the output.
2. Run the cell and check.
3. If I miss it, read only that section again.
4. Finish with the checklist at the bottom.

**Topics in this notebook**
1. 1D, 2D, and 3D arrays
2. List vs array (`*` does different things)
3. Why NumPy is faster
4. Creating arrays: zeros, ones, full, random, arange
5. Vector, matrix, tensor
6. Properties: shape, size, ndim, dtype, itemsize, nbytes
7. reshape, flatten, ravel, transpose

In [9]:
import numpy as np

## 1. 1D, 2D, and 3D arrays

An array is a block of numbers, all the same type.

- **1D** — one line of numbers. Shape looks like `(5,)`.
- **2D** — a table. Shape `(2, 3)` means 2 rows and 3 columns.
- **3D** — a stack of tables. Shape `(2, 2, 3)` means 2 tables, each 2×3.

`np.array(...)` turns a Python list into an array.
Printing an array has **no commas** between numbers. A list does.

In [11]:
ARRAY_1D = np.array([1, 2, 3, 4, 5])
print("1D Array:", ARRAY_1D)

ARRAY_2D = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:", ARRAY_2D)

ARRAY_3D = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D Array:", ARRAY_3D)

1D Array: [1 2 3 4 5]
2D Array: [[1 2 3]
 [4 5 6]]
3D Array: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## 2. Python list vs NumPy array

Same `*` sign. Two different jobs.

- List: `[1, 2, 3] * 2` **repeats** the list → `[1, 2, 3, 1, 2, 3]`
- Array: `np.array([1, 2, 3]) * 2` **multiplies each number** → `[2, 4, 6]`

I need this for ML. A model multiplies many numbers at once, not one Python loop at a time.

In [3]:
py_list = [1, 2, 3]
print("Python List:", py_list * 2)

np_array = np.array([1, 2, 3])
print("Numpy Array:", np_array * 2)

Python List: [1, 2, 3, 1, 2, 3]
Numpy Array: [2 4 6]


## 3. Why NumPy is faster

Python visits each list item in the interpreter.
NumPy runs the same math in compiled code over one block of memory.

On 10 million numbers in this run:

- Python list: about **0.11 s**
- NumPy array: about **0.005 s**

The exact seconds change every run. The point does not: for big numeric work, use an array.

In [4]:
import time
start_time = time.time()
py_list = [i*2 for i in range(10000000)]
end_time = time.time()
print(f"Time taken for Python list: {end_time - start_time} seconds")

start_time = time.time()
np_array = np.arange(10000000) * 2
end_time = time.time()
print(f"Time taken for Numpy array: {end_time - start_time} seconds")

Time taken for Python list: 0.11459684371948242 seconds
Time taken for Numpy array: 0.014462947845458984 seconds


## 4. Creating arrays

I do not always type the numbers by hand.

| Call | What I get |
| --- | --- |
| `np.zeros((3, 4))` | 3×4 of `0.` (float) |
| `np.ones((2, 3, 4))` | 2 blocks of 3×4 ones (float) |
| `np.full((2, 3), 5)` | 2×3 filled with `5` (int, because 5 is an int) |
| `np.random.rand(2, 3)` | 2×3 random floats from 0 to 1 |
| `np.arange(0, 10, 2)` | `0, 2, 4, 6, 8` — **10 is not included** |

Shape is a tuple. `(rows, cols)` for 2D. `(blocks, rows, cols)` for 3D.
`arange(start, stop, step)` stops **before** `stop`.

In [5]:
create_zeros_array = np.zeros((3, 4))
print("ZEROS_ARRAY_CREATED:::: \n", create_zeros_array)

create_ones_array = np.ones((2, 3, 4))
print("ONES_ARRAY_CREATED:::: \n", create_ones_array)

create_full_array = np.full((2, 3), 5)
print("FULL_ARRAY_CREATED:::: \n", create_full_array)

create_random_array = np.random.rand(2, 3)
print("RANDOM_ARRAY_CREATED:::: \n", create_random_array)

create_sequence_array = np.arange(0, 10, 2)
print("SEQUENCE_ARRAY_CREATED:::: \n", create_sequence_array)

ZEROS_ARRAY_CREATED:::: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ONES_ARRAY_CREATED:::: 
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
FULL_ARRAY_CREATED:::: 
 [[5 5 5]
 [5 5 5]]
RANDOM_ARRAY_CREATED:::: 
 [[0.81429143 0.26587395 0.33864041]
 [0.77200929 0.3912724  0.84016155]]
SEQUENCE_ARRAY_CREATED:::: 
 [0 2 4 6 8]


## 5. Vector, matrix, and tensor

These are the same arrays, with the names used in ML.

| Name | What it is | `ndim` |
| --- | --- | --- |
| **Vector** | 1D array | 1 |
| **Matrix** | 2D array | 2 |
| **Tensor** | 3D or more | 3+ |

A picture batch is often a tensor: many images, each with height, width, and color channels.

In [6]:
vector = np.array([1, 2, 3])
print("VECTOR:::: \n", vector)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("MATRIX:::: \n", matrix)

# Multi-dimensional array
tensor = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("TENSOR:::: \n", tensor)

VECTOR:::: 
 [1 2 3]
MATRIX:::: 
 [[1 2 3]
 [4 5 6]]
TENSOR:::: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## 6. Array properties

I keep one example in my head: `arr = [[1, 2, 3], [4, 5, 6]]`.

| Property | Question it answers | This example |
| --- | --- | --- |
| `shape` | How long is each axis? | `(2, 3)` |
| `size` | How many numbers in total? | `6` |
| `ndim` | How many axes? | `2` |
| `dtype` | What type is each number? | `int64` |
| `itemsize` | How many bytes is one number? | `8` |
| `nbytes` | How many bytes is the whole array? | `48` |

Two checks I use when revising:

- `size` = multiply the numbers in `shape` → `2 * 3 = 6`
- `nbytes` = `size * itemsize` → `6 * 8 = 48`

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:::: ", arr.shape)
print("Size:::: ", arr.size)
print("Dimensions:::: ", arr.ndim)
print("Data Type:::: ", arr.dtype)
print("Item Size:::: ", arr.itemsize)
print("Total Size:::: ", arr.nbytes)

Shape::::  (2, 3)
Size::::  6
Dimensions::::  2
Data Type::::  int64
Item Size::::  8
Total Size::::  48


## 7. Reshape, flatten, ravel, transpose

`np.arange(12)` is `[0, 1, 2, ..., 11]`.

- **`reshape(3, 4)`** — same 12 numbers, new shape. `3 * 4` must equal `12`. Fills **row by row**.
- **`flatten()`** — back to 1D. This is a **copy**. Changing it does not change the original.
- **`ravel()`** — also 1D, but usually a **view**. Changing it can change the original.
- **`.T`** — transpose. Rows become columns. `(3, 4)` becomes `(4, 3)`.

The one line I rewrite when I forget: **flatten copies, ravel views**.

In [8]:
arr = np.arange(12)
print("ORIGINAL_ARRAY:::: \n", arr)

reshaped_array = arr.reshape(3, 4)
print("RESHAPED_ARRAY:::: \n", reshaped_array)

flattened_array = reshaped_array.flatten()
print("FLATTENED_ARRAY:::: \n", flattened_array)

# ravel returns a view, instead of a copy
raveled_array = reshaped_array.ravel()
print("RAVELLED_ARRAY:::: \n", raveled_array)

# Transpose
transposed_array = reshaped_array.T
print("TRANSPOSED_ARRAY:::: \n", transposed_array)

ORIGINAL_ARRAY:::: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
RESHAPED_ARRAY:::: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
FLATTENED_ARRAY:::: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
RAVELLED_ARRAY:::: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
TRANSPOSED_ARRAY:::: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Revision checklist

Cover the answers. Say them out loud. Then uncover.

1. What does `*` do to a list? To an array?
2. What shape is `np.zeros((3, 4))`, and is it int or float?
3. Does `np.arange(0, 10, 2)` include `10`?
4. Vector, matrix, tensor — which `ndim` is each?
5. For `[[1, 2, 3], [4, 5, 6]]` of `int64`: `shape`, `size`, `nbytes`?
6. `flatten` or `ravel` — which one copies?
7. Shape after `.T` on a `(3, 4)` array?

<details>
<summary>Answers</summary>

1. List repeats. Array multiplies each value.
2. Shape `(3, 4)`, dtype float (`0.`).
3. No. Result is `[0, 2, 4, 6, 8]`.
4. Vector `1`, matrix `2`, tensor `3` or more.
5. `shape (2, 3)`, `size 6`, `nbytes 48` (`6 * 8`).
6. `flatten` copies. `ravel` is usually a view.
7. `(4, 3)`.

</details>

**Still to add later:** a forward pass. Broadcasting and matrix math are in `03_axis_vectors.ipynb`.