# NumPy array operations — my revision notes

I wrote these so I can come back and revise without re-learning from scratch.
Each section is: **what I need to remember**, then the code I already ran.

**How to revise**
1. Read the bullets. Cover the code and try to predict the output.
2. Run the cell and check.
3. If I miss it, read only that section again.
4. Finish with the checklist at the bottom.

**Topics in this notebook**
1. Slicing a 1D array
2. Rows, columns, and one cell in a 2D array
3. Sorting by row and by column
4. Filtering with a condition
5. Fancy indexing vs `np.where`
6. Adding data: concatenate, vstack, hstack
7. Shape must match
8. Deleting items

In [ ]:
import numpy as np

## 1. Slicing a 1D array

Array: `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`. Indexes start at **0**.

- `arr[2:7]` — from index 2 up to, but **not including**, 7 → `[3, 4, 5, 6, 7]`
- `arr[-3]` — third item from the end → `8` (this is one item, not a slice)
- `arr[1:8:2]` — from index 1 to 8, step 2 → `[2, 4, 6, 8]`

Pattern: `start:stop:step`. `stop` is never included.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing:::: ", arr[2:7])
print("Negative Slicing: ", arr[-3])
print("Step Slicing::::: ", arr[1:8:2])

Basic Slicing::::  [3 4 5 6 7]
Negative Slicing:  8
Step Slicing:::::  [2 4 6 8]


## 2. Rows, columns, and one cell

For a 2D array, the index is `[row, column]`.

```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

- `arr_2d[1, 2]` — row 1, column 2 → `6`
- `arr_2d[1]` — the whole row 1 → `[4, 5, 6]`
- `arr_2d[:, 1]` — **every row**, column 1 → `[2, 5, 8]`

`:` means “all”. So `[:, 1]` is a column, not a row.

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Specific Element:::: ", arr_2d[1, 2])
print("Specific Row:::: ", arr_2d[1])
print("Specific Column:::: ", arr_2d[:, 1])

Specific Element::::  6
Specific Row::::  [4 5 6]
Specific Column::::  [2 5 8]


## 3. Sorting

`np.sort` returns a **new** sorted array. It does not change the original.

- 1D: smallest to largest.
- 2D default `axis=1`: sort **each row** left to right.
- `axis=0`: sort **each column** top to bottom.

On `[[3, 1, 2], [1, 15, 9], [7, 6, 4]]`:

- by row → `[[1, 2, 3], [1, 9, 15], [4, 6, 7]]`
- by column → `[[1, 1, 2], [3, 6, 4], [7, 15, 9]]`

Column sort does **not** keep a row together. Each column is sorted on its own.

In [ ]:
unsorted_array = np.array([3, 1, 2, 1, 5, 9, 7, 6, 4])
print("Sorted Array:::: ", np.sort(unsorted_array))

unsorted_array_2d = np.array([[3, 1, 2], [1, 15, 9], [7, 6, 4]])
print("Sorted 2D Array By Row:::: ", np.sort(unsorted_array_2d))
print("Sorted 2D Array By Column:::: ", np.sort(unsorted_array_2d, axis=0))

Sorted Array::::  [1 1 2 3 4 5 6 7 9]
Sorted 2D Array By Row::::  [[ 1  2  3]
 [ 1  9 15]
 [ 4  6  7]]
Sorted 2D Array By Column::::  [[ 1  1  2]
 [ 3  6  4]
 [ 7 15  9]]


## 4. Filtering with a condition

A condition on an array makes a **mask** of `True` / `False`, one flag per item.
Putting that mask inside `[]` keeps only the `True` items.

- `numbers % 2 == 0` keeps evens → `[2, 4, 6, 8, 10]`
- `numbers > 5` keeps bigger than 5 → `[6, 7, 8, 9, 10]`

I can store the mask first (`mask = numbers > 5`) and reuse it.

In [ ]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Filtered Even Numbers:::: ", numbers[numbers % 2 == 0])

# Filter with mask
mask = numbers > 5
print("Filtered Numbers Greater Than 5:::: ", numbers[mask])

Filtered Even Numbers::::  [ 2  4  6  8 10]
Filtered Numbers Greater Than 5::::  [ 6  7  8  9 10]


## 5. Fancy indexing vs `np.where`

Three different jobs. I mix these up, so I keep them separate.

- **Fancy indexing** — I already know the indexes. `numbers[[0, 2, 4]]` → `[1, 3, 5]`
- **Boolean filter** (section 4) — I want the **values** that pass a test.
- **`np.where(condition)`** — I want the **indexes** where the test is true.
  `numbers > 5` is true at indexes 5 through 9, so the result is `(array([5, 6, 7, 8, 9]),)`.
  It is a tuple because a 2D array would return one index array per axis.
- **`np.where(condition, if_true, if_false)`** — pick a value per item.
  Above 5, multiply by 10. Otherwise keep the number.
  → `[1, 2, 3, 4, 5, 60, 70, 80, 90, 100]`

In [ ]:
indices = [0, 2, 4]
print("Fancy Indexing:::: ", numbers[indices])

where_result = np.where(numbers > 5)
print("np.where() Result:::: ", where_result)

Fancy Indexing::::  [1 3 5]
np.where() Result::::  (array([5, 6, 7, 8, 9]),)


In [ ]:
condition_array = np.where(numbers > 5, numbers * 10, numbers)
print("Condition Array:::: ", condition_array)

Condition Array::::  [  1   2   3   4   5  60  70  80  90 100]


## 6. Adding data

These return a **new** array. The originals stay as they were.

- `np.concatenate((arr1, arr2))` — join 1D arrays end to end → `[1, 2, 3, 4, 5, 6]`
- `np.vstack` — stack **rows**. New row must have the same number of columns.
  `[[1, 2], [3, 4]]` plus `[[5, 6]]` → 3 rows, 2 columns.
- `np.hstack` — stack **columns**. New column must have the same number of rows.
  plus `[[7], [8]]` → 2 rows, 3 columns: `[[1, 2, 7], [3, 4, 8]]`

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("Concatenation:::: ", np.concatenate((arr1, arr2)))

Concatenation::::  [1 2 3 4 5 6]


## 7. Shape must match

Before I stack or do item-by-item math, the shapes have to agree.

- `a`, `b`, and `c` are all shape `(3,)` → compatible with each other.
- `d` is shape `(4,)` → not compatible with them.

`a.shape == b.shape` is `True` only when both tuples are identical.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
d = np.array([10, 11, 12, 13])
print("Compatibility Shape:::: ", a.shape == b.shape)
print("Compatibility Shape:::: ", a.shape == b.shape == c.shape)
print("Compatibility Shape:::: ", a.shape == b.shape == c.shape == d.shape)

Compatibility Shape::::  True
Compatibility Shape::::  True
Compatibility Shape::::  False


In [ ]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))
print("With New Row Array:::: ", with_new_row)

new_column = np.array([[7], [8]])
with_new_column = np.hstack((original, new_column))
print("With New Column Array:::: ", with_new_column)

With New Row Array::::  [[1 2]
 [3 4]
 [5 6]]
With New Column Array::::  [[1 2 7]
 [3 4 8]]


## 8. Deleting items

`np.delete(arr, index)` returns a **new** array. `arr` itself is unchanged.

On `[1, 2, 3, 4, 5]`:

- delete index `2` → drop `3` → `[1, 2, 4, 5]`
- delete indexes `[2, 3]` → drop `3` and `4` → `[1, 2, 5]`

The argument is the **index**, not the value.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print("Array After Deletion:::: ", deleted)

deleted_elements = np.delete(arr, [2, 3])
print("Array After Deletion Of Elements:::: ", deleted_elements)

Array After Deletion::::  [1 2 4 5]
Array After Deletion Of Elements::::  [1 2 5]


## Revision checklist

Cover the answers. Say them out loud. Then uncover.

1. What is `arr[2:7]` on `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`? Is the stop included?
2. In a 2D array, what does `[:, 1]` select?
3. `np.sort` on a 2D array: what is the default axis, and what does `axis=0` do?
4. How do I keep only the even numbers?
5. Fancy index vs `np.where(condition)` vs `np.where(condition, a, b)` — what does each return?
6. `vstack` or `hstack` — which adds a row?
7. Does `np.delete` change the original array?

<details>
<summary>Answers</summary>

1. `[3, 4, 5, 6, 7]`. Stop is not included.
2. Column 1, every row.
3. Default `axis=1` sorts each row. `axis=0` sorts each column.
4. `numbers[numbers % 2 == 0]`.
5. Fancy index returns the **values** at those indexes. `np.where(condition)` returns the **indexes**. The 3-argument form returns **new values** chosen by the condition.
6. `vstack` adds a row. `hstack` adds a column.
7. No. It returns a new array.

</details>